### ISSUE TITLE
Integration Changes

### ISSUE THREAD

**Issue by chamathpali** [isee4xai/iSeeBackend#7]
### Highlevel Tasks Summary
1. All requests are in JSON not form-data except for file upload
2. All responses has type to indicate in which data type we get the response
3. List of possible types are dict and image for now

### Tasks

- [x] Model upload should accept full URI for ai_task, dataset_type, framework
- [x] Document all file upload types and change request body as suggested to JSON
- [x] Get number of instances: change response to a JSON format as suggested
- [x] Get number of instances for a zipped folder to be implemented
- [x] Get instance: response format changed to JSON as suggested: when tabular, change instance to key values pairs; when Image change instance to BASE64 and send feature size or size_raw as size. Get instance from zipped folder to be implemented
- [x] Get prediction: change response to suggested

### Explainer related:
- [x] GradCAMTorch change to GradCAM with torch and TensorFlow implementations
- [ ] Don’t use isee4xai as a explainer repo, move foxcbx like implementations out of isee4xai organisation 
- [x] Superimpose attributions on images for IntG and GradCam

**Comment by chamathpali** [comment]
@jesusdarias over to you 👋

**Comment by anjanaw** [comment]
Here is the GradCam implementation for Tensorflow models, also it has code to superimpose attributions in to the original image which can be adapted for Integrated gradients. Let me know if you have any questions. https://colab.research.google.com/drive/1UaawPskfU6AfrPNGvhNJET_7Xk9N6NpT?usp=sharing
